apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/part-of: taxi
      app.kubernetes.io/version: 0.0.3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/part-of: taxi
        app.kubernetes.io/version: 0.0.3
    spec:
      containers:
      - image: bigkevmcd/image-hooks:latest
        imagePullPolicy: Always
        name: taxi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
