apiVersion: v1
kind: Service
metadata:
  name: taxi
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: "0.0.3"
spec:
  selector:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/version: "0.0.3"
  ports:
  - port: 8080
    protocol: TCP
    name: http
